### ISSUE TITLE
Dockerized deployment

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/containers#1]
### Proposed solution

OpenRefine runs on baremetal machine, seeing the current trends having a dockerised deployment is no longer considered a feature yet a basic requirement from any well-used project. Proposal to have a Dockerfile & containerised way to run openrefine on user local system. As well as setup a dockerhub repo to push latest images for openrefine.

### Additional context

- This thread is to initialise a discussion on having containerised deployments for OpenRefine.
- Would love to get feedback from the community, on the idea.

**Comment by wetneb** [comment]
I think it could be nice to officially support running with Docker. I suspect it should not be too much work maintaining the Dockerfile. It would probably add a step in the release process though (build the image and push it to the Docker repository).

**Comment by elroykanye** [comment]
@kushthedude , are you still working on this?

**Comment by frafra** [comment]
I made that: https://github.com/NINAnor/openrefine.
Docker image can be found here: https://github.com/NINAnor/openrefine/pkgs/container/openrefine

It would be nice to build it using maven instead of fetching the tarball of the latest stable release.

**Comment by sepastian** [comment]
Any progress on this?

**Comment by frafra** [comment]
Well, I updated my Dockerfile so that OpenRefine is built from sources, and I build multiple versions and branches using GitHub actions and GitHub registry: https://github.com/NINAnor/openrefine/pkgs/container/openrefine/versions. It works just fine for me. Feedback is welcome. I can make a PR here if the maintainers like the approach I used.

**Comment by wetneb** [comment]
If you are building with maven, then you probably don't need to run `mvn package` but just `./refine build`. The `package` goal generates the `.zip` files for Windows, `.tar.gz` files for Linux and `.dmg` for MacOS, but you are not relying on any of those in the rest of the Docker image, so it's likely just taking more time in your build and inflating the image size unnecessarily.

In terms of providing official support for it in the OpenRefine project, maybe we could have a separate repository for it - perhaps where other packaging configurations (flatpak, appimage…) could live.

**Comment by frafra** [comment]
Thank you; I am now using `mvn -B process-resources compile test-compile`, since `./refine build` calls `npm` to build the frontend, which is done in a different stage of the container. I could also copy fewer files probably: https://github.com/NINAnor/openrefine/blob/883c18495a2e84e122a20b0bcc09c49d1a8e1d70/Dockerfile#L21-L24.

I can maintain the Docker repository (we are using these images in production and for testing internal APIs across different versions), and then you can move it to the OpenRefine organization when you consider that ready.

Caching of dependencies needs to be improved, but I am not familiar with maven, so it would be easier if I could get some help with that. Having an initial goal to fetch only dependencies and then avoid connecting to the internet entirely would be great.

**Comment by sepastian** [comment]
> If you are building with maven, then you probably don't need to run `mvn package` but just `./refine build`. The `package` goal generates the `.zip` files for Windows, `.tar.gz` files for Linux and `.dmg` for MacOS, but you are not relying on any of those in the rest of the Docker image, so it's likely just taking more time in your build and inflating the image size unnecessarily.
> 
> In terms of providing official support for it in the OpenRefine project, maybe we could have a separate repository for it - perhaps where other packaging configurations (flatpak, appimage…) could live.

+1 for a separate repository containing build/packaging files.

**Comment by wetneb** [comment]
The repository is now created, so I am migrating this issue there:
https://github.com/OpenRefine/containers
Feel free to open a PR to add a Dockerfile there.

**Comment by frafra** [comment]
Added Dockerfile and GitHub CI. Getting there! :)

https://github.com/OpenRefine/containers/pull/3

**Comment by heryk** [comment]
Hello, I'm getting error messages when trying to run the docker-compose.yml file (docker-compose up -d). 

_Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.13_

Any idea of what is going on?
Thanks

`$ docker-compose up -d
[+] Building 48.5s (20/26)                                                                                                   docker:default
 => [openrefine internal] load build definition from Dockerfile                                                                        0.1s
 => => transferring dockerfile: 1.47kB                                                                                                 0.0s
 => [openrefine internal] load .dockerignore                                                                                           0.1s
 => => transferring context: 2B                                                                                                        0.0s
 => [openrefine internal] load metadata for registry.opensuse.org/opensuse/bci/openjdk:latest                                          3.7s
 => [openrefine internal] load metadata for registry.opensuse.org/opensuse/bci/nodejs:latest                                           3.6s
 => [openrefine internal] load metadata for registry.opensuse.org/opensuse/bci/openjdk-devel:latest                                    3.7s
 => [openrefine internal] load metadata for registry.opensuse.org/opensuse/git:latest                                                  3.6s
 => [openrefine stage-3 1/8] FROM registry.opensuse.org/opensuse/bci/openjdk:latest@sha256:ec56dcc7c24ebcd50b1741ebc2af06e969c485382  38.1s
 => => resolve registry.opensuse.org/opensuse/bci/openjdk:latest@sha256:ec56dcc7c24ebcd50b1741ebc2af06e969c485382f6d11f7e47242bd63158  0.1s
 => => sha256:ec56dcc7c24ebcd50b1741ebc2af06e969c485382f6d11f7e47242bd6315824c 1.42kB / 1.42kB                                         0.0s
 => => sha256:ae8fb7f89475c84a346036a703d4644b1f0fd52eef67c38dd5f7fcc1f0f2b8ca 755B / 755B                                             0.0s
 => => sha256:c783d33ac11799a2f79dbde6c8e987ae349330d4ea287b26a4e7202de83e45b5 13.98kB / 13.98kB                                       0.0s
 => => sha256:0f0de3fafa7ab7408b98c033da6b964db79b861031356910b07f32e470d02008 49.21MB / 49.21MB                                      19.3s
 => => sha256:e701d34700d694820acafc29eea17fa6bdcafa4fdcfbdf03c42db1c8151964ed 73.11MB / 73.11MB                                      35.9s
 => => extracting sha256:0f0de3fafa7ab7408b98c033da6b964db79b861031356910b07f32e470d02008                                              1.6s
 => => extracting sha256:e701d34700d694820acafc29eea17fa6bdcafa4fdcfbdf03c42db1c8151964ed                                              1.8s
 => [openrefine internal] load build context                                                                                           0.1s
 => => transferring context: 1.90kB                                                                                                    0.0s
 => [openrefine backend 1/4] FROM registry.opensuse.org/opensuse/bci/openjdk-devel:latest@sha256:b6be812c5f0d8a9f7f7f62edc02de04485e  38.5s
 => => resolve registry.opensuse.org/opensuse/bci/openjdk-devel:latest@sha256:b6be812c5f0d8a9f7f7f62edc02de04485efeabf6eab9474aa1a1fc  0.2s
 => => sha256:0f0de3fafa7ab7408b98c033da6b964db79b861031356910b07f32e470d02008 49.21MB / 49.21MB                                      19.3s
 => => sha256:e701d34700d694820acafc29eea17fa6bdcafa4fdcfbdf03c42db1c8151964ed 73.11MB / 73.11MB                                      35.8s
 => => sha256:c89052aabd23ae5d0b5ac28b032febd5825584a416fe96d29170372f1ebaf5ca 30.54MB / 30.54MB                                      22.6s
 => => sha256:b6be812c5f0d8a9f7f7f62edc02de04485efeabf6eab9474aa1a1fce0b79a112 1.42kB / 1.42kB                                         0.0s
 => => sha256:83319043cbd3d2fc92d8ea1498800b1a45a0900438199ec21f52978a72092cab 970B / 970B                                             0.0s 
 => => sha256:383611c1dc5ba2df8ea91b2dba587ae3951cfa8584435d4dbf84a67f877b64b0 23.23kB / 23.23kB                                       0.0s 
 => => extracting sha256:0f0de3fafa7ab7408b98c033da6b964db79b861031356910b07f32e470d02008                                              1.6s 
 => => extracting sha256:e701d34700d694820acafc29eea17fa6bdcafa4fdcfbdf03c42db1c8151964ed                                              8.5s 
 => => extracting sha256:c89052aabd23ae5d0b5ac28b032febd5825584a416fe96d29170372f1ebaf5ca                                              0.4s 
 => [openrefine frontend 1/4] FROM registry.opensuse.org/opensuse/bci/nodejs:latest@sha256:f37491fe3c9b2cfce9b4df2ccce7681481a2c77b2  40.7s 
 => => resolve registry.opensuse.org/opensuse/bci/nodejs:latest@sha256:f37491fe3c9b2cfce9b4df2ccce7681481a2c77b2d5d0962565b03b3ee12c4  0.2s 
 => => sha256:f37491fe3c9b2cfce9b4df2ccce7681481a2c77b2d5d0962565b03b3ee12c459 1.76kB / 1.76kB                                         0.0s 
 => => sha256:fd5222b70cedbc4be3c5a62908c2f23b92824274f3a088e3db3fade2416e8f83 755B / 755B                                             0.0s 
 => => sha256:21a604445140cd704b06b8dfc5fe5cc9460ddb40a371454091cc72a578dbe800 13.00kB / 13.00kB                                       0.0s 
 => => sha256:0f0de3fafa7ab7408b98c033da6b964db79b861031356910b07f32e470d02008 49.21MB / 49.21MB                                      19.3s 
 => => extracting sha256:0f0de3fafa7ab7408b98c033da6b964db79b861031356910b07f32e470d02008                                              1.6s 
 => => sha256:7241ff6d95ea4e03977b59fc74783bb3412c0cd48ca142dbda879cf2cf0a4756 45.47MB / 45.47MB                                      38.6s 
 => => extracting sha256:7241ff6d95ea4e03977b59fc74783bb3412c0cd48ca142dbda879cf2cf0a4756                                              1.6s 
 => [openrefine sources 1/3] FROM registry.opensuse.org/opensuse/git:latest@sha256:92f3f08fd3e3bcef13303a4726de1c982b48130d4cc9a0223  32.3s 
 => => resolve registry.opensuse.org/opensuse/git:latest@sha256:92f3f08fd3e3bcef13303a4726de1c982b48130d4cc9a022335650dec79555ec       0.2s 
 => => sha256:92f3f08fd3e3bcef13303a4726de1c982b48130d4cc9a022335650dec79555ec 1.76kB / 1.76kB                                         0.0s 
 => => sha256:8ec17574fafc1c5f6a5e82c12621a74363b93afd47afd2fb8c0eec01658eb792 754B / 754B                                             0.0s 
 => => sha256:e8e64b3d733963bfe91eb3831a3a97614efb155db8f60322a43c55c570e418e6 3.77kB / 3.77kB                                         0.0s 
 => => sha256:5b61929b5ce78ddbce29263e8596d7498f06da551e107a671317f81d08c930a7 11.40MB / 11.40MB                                      24.5s 
 => => sha256:13c548a39054c35d0829bef92346fffe706b9c72854c71db44e015af40bda1f3 18.57MB / 18.57MB                                      31.6s 
 => => extracting sha256:5b61929b5ce78ddbce29263e8596d7498f06da551e107a671317f81d08c930a7                                              0.7s 
 => => extracting sha256:13c548a39054c35d0829bef92346fffe706b9c72854c71db44e015af40bda1f3                                              0.3s 
 => [openrefine sources 2/3] WORKDIR /opt/openrefine                                                                                   0.1s 
 => [openrefine sources 3/3] RUN git clone https://github.com/OpenRefine/OpenRefine.git --depth 1 --branch master .                    5.1s 
 => CANCELED [openrefine stage-3 2/8] RUN zypper --non-interactive install gettext-tools which                                         6.5s 
 => [openrefine backend 2/4] WORKDIR /opt/openrefine                                                                                   0.1s 
 => [openrefine backend 3/4] COPY --from=sources /opt/openrefine .                                                                     0.2s 
 => ERROR [openrefine backend 4/4] RUN --mount=type=cache,target=/root/.m2     mvn -B process-resources compile test-compile           5.7s 
 => [openrefine frontend 2/4] WORKDIR /opt/openrefine/main/webapp                                                                      0.2s 
 => [openrefine frontend 3/4] COPY --from=sources /opt/openrefine/main/webapp .                                                        0.1s 
 => CANCELED [openrefine frontend 4/4] RUN --mount=type=cache,target=/root/.npm     npm install                                        3.6s 
------
 > [openrefine backend 4/4] RUN --mount=type=cache,target=/root/.m2     mvn -B process-resources compile test-compile:
1.349 [INFO] Scanning for projects...
1.605 [INFO] Downloading from jenkins-repo: https://repo.jenkins-ci.org/releases/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.13/nexus-staging-maven-plugin-1.6.13.pom
5.285 [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.13/nexus-staging-maven-plugin-1.6.13.pom
5.656 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
5.656 [ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13 or one of its dependencies could 
not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.13 @
5.656  @
5.657 [ERROR] The build could not read 1 project -> [Help 1]
5.657 [ERROR]
5.657 [ERROR]   The project org.openrefine:openrefine:3.8-SNAPSHOT (/opt/openrefine/pom.xml) has 1 error
5.657 [ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.13: The following artifacts could not be resolved: org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.13 (absent): Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.13 from/to jenkins-repo (https://repo.jenkins-ci.org/releases/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 2]
5.657 [ERROR]
5.657 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
5.657 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
5.657 [ERROR]
5.657 [ERROR] For more information about the errors and possible solutions, please read the following articles:
5.657 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
5.657 [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
------
failed to solve: process "/bin/sh -c mvn -B process-resources compile test-compile" did not complete successfully: exit code: 1`

**Comment by heryk** [comment]
Hi, I get the following log error message in my container when trying to run the docker compose file.
Any idea what is going wrong?
Thanks

```
2024-01-23 11:30:17 openrefine-1  | + template=refine.ini.template
2024-01-23 11:30:17 openrefine-1  | + '[' -f refine.ini.template ']'
2024-01-23 11:30:17 openrefine-1  | + envsubst
2024-01-23 11:30:17 openrefine-1  | + exec /opt/openrefine/refine -i 0.0.0.0 -d /workspace run
2024-01-23 11:30:17 openrefine-1  | Using refine.ini for configuration
2024-01-23 11:30:17 openrefine-1  | No host specified while binding to interface 0.0.0.0, guessing localhost.
2024-01-23 11:30:17 openrefine-1  | -------------------------------------------------------------------------------------------------
2024-01-23 11:30:17 openrefine-1  | You have 31939M of free memory.
 of memory.11:30:17 openrefine-1  | Your current configuration is set to use 2000M
2024-01-23 11:30:17 openrefine-1  | OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
2024-01-23 11:30:17 openrefine-1  | https://openrefine.org/docs/manual/installing#increasing-memory-allocation
2024-01-23 11:30:17 openrefine-1  | -------------------------------------------------------------------------------------------------
2024-01-23 11:30:17 openrefine-1  | 
2024-01-23 11:30:17 openrefine-1  | Invalid initial heap size: -Xms2000M
2024-01-23 11:30:17 openrefine-1  | Error: Could not create the Java Virtual Machine.
2024-01-23 11:30:17 openrefine-1  | Error: A fatal exception has occurred. Program will exit.
```

**Comment by frafra** [comment]
@heryk I cannot reproduce; are you on a 32 bit system?

**Comment by frafra** [comment]
I updated https://github.com/ninanor/openrefine. I have been using it in production for a while, and updated through various versions. Images for 3.8, 3.8.2 and master are published on the GitHub Registry.

I do not see the images being published here, which would be nice. Could it be that the image is not publicly shared?

**Comment by wetneb** [comment]
Hi @frafra,

I don't know what could prevent the image hosted in this repository from being publicly shared. I don't have experience with publishing container images on GitHub. Would you like to be part of the OpenRefine org so that you can apply any necessary fixes to this repository?

**Comment by frafra** [comment]
Sure @wetneb, I can do it and if needed to be a maintainer of this repository.

**Comment by wetneb** [comment]
Great! I've sent you an invite as admin of this repository and another one to be member of the OpenRefine org.

**Comment by frafra** [comment]
I cannot change the visibility of the image because it is prevented by the settings at the organization level:

![image](https://github.com/user-attachments/assets/46c30cdd-e753-481a-8723-fb3ccfe0f827)

Could you please check that? I think you should be able to change it under https://github.com/organizations/OpenRefine/settings/packages

**Comment by wetneb** [comment]
Indeed! I have just enabled Public and Internal packages.

**Comment by frafra** [comment]
Problem solved. I think we can close this issue then.
